# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

aliases:
  - &working_directory
    ~/repo

  - &restore_cache
    keys:
    - v1-dependencies-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

  - &npm_install
    name: Install Packages
    command: npm install

  - &save_cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

  - &tag_filters
    branches:
      ignore: /.*/
    tags:
      only: /^v?[0-9]+(\.[0-9]+)*/

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: regviz/node-xcb

  working_directory: *working_directory

jobs:

  storybook-build-screenshot:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Check versions
          command: |
            node --version
            npm --version
            # docker --version
            # yarn --version

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache

      - run:
          name: Build
          command: |
            npm run storybook-build
            npm run storybook-screenshot-static

      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
      # taken to be the root directory of the workspace.
      - persist_to_workspace:
          root: *working_directory
          paths:
            - .out
            - __screenshots__

  deploy-github-pages:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache
        
      - run:
          name: Deploy GitHub Pages
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            npm run storybook-build
            npm run storybook-deploy

  release-github-assets:
    <<: *defaults

    steps:
      - checkout

      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: .

      # Download and cache dependencies
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache
        
      - run:
          name: Add GitHub Release assets
          command: npm run upload-release-assets

# Workflows enable multiple jobs in parallel
workflows:
  version: 2
  deploy:
    jobs:
      - storybook-build-screenshot:
          # Note: The build job must also have a filters tags section, as it is a transient dependency of the deploy job.
          filters: *tag_filters

      # - deploy-github-pages:
      #     requires:
      #       - build

      # - npm-publish:
      #     requires:
      #       - build
      #     filters: *tag_filters

      # - release-github-assets:
      #     requires:
      #       - build
      #     filters: *tag_filters

